### ISSUE TITLE
No longer able to build due changed psysh URL

### ISSUE THREAD

**Issue by Germano0** [BOINC/boinc-server-test#4]
Good day,
from 2 days I am no longer able to run
`ansible-playbook -i hosts build.yml`
due
`[previous messages cutted] "The following extra packages will be installed:", "  libssl1.0.0", "The following packages will be upgraded:", "  libssl1.0.0 openssl", "2 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.", "Need to get 1982 kB of archives.", "After this operation, 420 kB of additional disk space will be used.", "Get:1 http://ftp.debian.org/debian/ jessie-backports/main libssl1.0.0 amd64 1.0.2l-1~bpo8+1 [1295 kB]", "Get:2 http://ftp.debian.org/debian/ jessie-backports/main openssl amd64 1.0.2l-1~bpo8+1 [687 kB]", "\u001b[91mdebconf: delaying package configuration, since apt-utils is not installed", "\u001b[0mFetched 1982 kB in 0s (2041 kB/s)", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 15319 files and directories currently installed.)", "Preparing to unpack .../libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb ...", "Unpacking libssl1.0.0:amd64 (1.0.2l-1~bpo8+1) over (1.0.1t-1+deb8u6) ...", "Preparing to unpack .../openssl_1.0.2l-1~bpo8+1_amd64.deb ...", "Unpacking openssl (1.0.2l-1~bpo8+1) over (1.0.1t-1+deb8u6) ...", "Setting up libssl1.0.0:amd64 (1.0.2l-1~bpo8+1) ...", "debconf: unable to initialize frontend: Dialog", "debconf: (TERM is not set, so the dialog frontend is not usable.)", "debconf: falling back to frontend: Readline", "Setting up openssl (1.0.2l-1~bpo8+1) ...", "Processing triggers for libc-bin (2.19-18+deb8u10) ...", "\u001b[91mconverted 'https://git.io/psysh' (ANSI_X3.4-1968) -> 'https://git.io/psysh' (UTF-8)", "--2018-10-09 08:12:49--  https://git.io/psysh", "\u001b[0m\u001b[91mResolving git.io (git.io)... \u001b[0m\u001b[91m34.206.9.96, 34.196.237.103, 34.204.22.7, ...", "Connecting to git.io (git.io)|34.206.9.96|:443... \u001b[0m\u001b[91mconnected.", "\u001b[0m\u001b[91mHTTP request sent, awaiting response... \u001b[0m\u001b[91m302 Found", "Location: https://raw.githubusercontent.com/bobthecow/psysh/gh-pages/psysh [following]", "converted 'https://raw.githubusercontent.com/bobthecow/psysh/gh-pages/psysh' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/bobthecow/psysh/gh-pages/psysh' (UTF-8)", "--2018-10-09 08:12:50--  https://raw.githubusercontent.com/bobthecow/psysh/gh-pages/psysh", "Resolving raw.githubusercontent.com (raw.githubusercontent.com)... \u001b[0m\u001b[91m151.101.0.133, 151.101.64.133, 151.101.128.133, ...", "Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... \u001b[0m\u001b[91mconnected.", "\u001b[0m\u001b[91mHTTP request sent, awaiting response... \u001b[0m\u001b[91m404 Not Found", "2018-10-09 08:12:50 ERROR 404: Not Found.", "", "\u001b[0m"]}`

(the bad formattation is not my fault, it's just the console output)

It looks like psysh maintainer erased the related Github page (gh-pages).
I have tried to adjust the dependency URL to https://psysh.org/psysh but I have not found any reference to psysh in boinc-server-test source code, so it should be triggered by other dependencies

**Comment by AenBleidd** [comment]
It is a dependency from https://github.com/marius311/boinc-server-docker/blob/master/images/apache/Dockerfile

CC: @marius311, could you please fix this if it's possible? Thanks

**Comment by TheAspens** [comment]
Actually - I need to adapt boinc-server-test to use the latest version of @marius311 docker-server.  I locked it onto a specific version of boinc-server so that boinc-server-test wouldn't break each time boinc-server advanced.  Let me take care of that and then we will see if something needs to be done with boinc-server.

**Comment by AenBleidd** [comment]
@TheAspens, the latest code in master from @marius311 repo still has the link to psysh

**Comment by TheAspens** [comment]
Ah - ok.   Then I need to update so that once @marius311 makes his changes, boinc-server-test will be able to pick up the changes.  It is work I've needed to do for awhile so this is good motivation.

**Comment by marius311** [comment]
> I locked it onto a specific version of boinc-server so that boinc-server-test wouldn't break each time boinc-server advanced

Fyi Im doing my best to respect semantic versioning in the b-s-d releases, if that info is of any help. 

> could you please fix this if it's possible? Thanks

Will try to do later today.

**Comment by TheAspens** [comment]
As a workaround until @marius311 is able to update boinc-server-docker, you can checkout branch knr_latest_boinc_server and follow the instructions in pull request #5

**Comment by TheAspens** [comment]
I updated my pull request to use a fork with the proposed fix.  You should be able to just checkout my branch knr_latest_boinc_server and use that as a workaround for the moment.

**Comment by marius311** [comment]
Just merged https://github.com/marius311/boinc-server-docker/pull/48, thanks.

**Comment by TheAspens** [comment]
@marius311 - can you create a release tag 3.0.2 so that I can point this repo to that tag?  Thanks!

**Comment by marius311** [comment]
@TheAspens Sorry catching up on some stuff post-moving. Just tagged 3.0.2 which includes the URL fix.
